spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agency-data
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    password: anhdmeroecfwmebs
    username: ulvisab@code.edu.az
    port: 587
  security:
    secret: bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNA==
    token:
      expirationTime: 60
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST_NAME:localhost}:${KAFKA_PORT:9092}
      properties:
        group-id: telegram-bot
    admin:
      properties:
        bootstrap.servers: ${KAFKA_HOST_NAME:localhost}:${KAFKA_PORT:9092}
server:
  port: 8081
